apiVersion: policy.kcloudlabs.io/v1alpha1
kind: ClusterValidatePolicy
metadata:
  name: test-delete-ns
  labels:
    kinitiras.kcloudlabs.io/webhook: enabled
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Pod # match all Pod | can add label to test in part of Pods
  validateRules:
    - targetOperations:
      - DELETE
      template:
        type: condition
        condition:
          cond: Exist # or NotExist
          message: "cannot delete this ns"
          dataRef:
            from: current
            # if the below field exist then resist the deletion operation
            # if cond == NotExist then rejects when field not exist
            path: "/metadata/annotations/no-delete"