apiVersion: policy.kcloudlabs.io/v1alpha1
kind: ClusterValidatePolicy
metadata:
  name: test-delete-ns
  labels:
    kinitiras.kcloudlabs.io/webhook: enabled
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Pod # match all Pod | can add label to test in part of Pods
      labelSelector:
        matchLabels:
          controller: test
  validateRules:
    - targetOperations:
        - DELETE
      template:
        type: pab
        podAvailableBadge:
          maxUnavailable: 50%
#          In most case, no need to set replica reference since webhook will try to get replica from
#          current pod owner reference spec.replica and status.replica.
#          Only when pod running with custom workload or no k8s workload(test) then set replica reference.
          replicaReference:
            from: http
            currentReplicaPath: "body.result.deployment.running_task_count"
            targetReplicaPath: "body.result.deployment.target_task_count"
            http:
              url: "http://192.168.0.107:8081/api/deployment/{{metadata.annotations.test_deployment}}"
              method: GET