apiVersion: v1
kind: Service
metadata:
  namespace: kinitiras-system
  name: kinitiras-webhook
spec:
  selector:
    controller: kinitiras-webhook
  ports:
    - name: webhook
      port: 8443
      targetPort: 8443
    - name: metrics
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kinitiras-system
  name: kinitiras-webhook
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  selector:
    matchLabels:
      controller: kinitiras-webhook
  replicas: 1
  template:
    metadata:
      labels:
        controller: kinitiras-webhook
    spec:
      serviceAccountName: kinitiras
      containers:
        - command:
            - ./webhook
          args:
            - --cert-dir=/certs
            - --v=4
            - --logtostderr=false
            - --alsologtostderr=true
            - --log_dir=./log
          image: docker.io/yusank/kinitiras-webhook:v0.1.2-01
          imagePullPolicy: IfNotPresent
          name: kinitiras-webhook
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 20Mi
          volumeMounts:
            - mountPath: /certs
              name: cert
              readOnly: true
            - mountPath: /kinitiras/log
              name: log
              subPathExpr: $(POD_NAME)
            - mountPath: /etc/templates
              name: templates
              readOnly: true
      volumes:
        - name: cert
          secret:
            secretName: kinitiras-webhook-cert
        - name: log
          hostPath:
            path: /var/log/kinitiras
            type: DirectoryOrCreate
        - name: templates
          hostPath:
            path: "/etc/templates"
            type: Directory