apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kinitiras-exporter
  namespace: kinitiras-system
spec:
  endpoints:
    - interval: 5s
      port: metrics
      scrapeTimeout: 2s
  selector:
    matchLabels:
      controller: kinitiras-webhook