apiVersion: v1
kind: Secret
metadata:
  name: kinitiras-webhook-cert
  namespace: kinitiras-system
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kinitiras
  namespace: kinitiras-system